---
# Task:  Install custom, locally provided sosreport packages,
#        whose local pathes are specified by the $rpm 
#        variables

- name: Copy sosreport RPM
  copy: src=$rpm dest=/var/tmp/{{ rpm|basename }}
  when: ansible_os_family == "RedHat"

- name: Install sosreport RPM
  yum:  name=/var/tmp/{{ rpm|basename }} state=present
  when: ansible_os_family == "RedHat"
